[pytest]
testpaths = server/tests pc-client/tests
python_files = test_*.py *_test.py
python_classes = Test*
python_functions = test_*

norecursedirs = scripts venv dist __pycache__

addopts = -v --tb=short
